# yamllint disable rule:line-length
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redpanda-http-sink-connector
  namespace: redpanda
spec:
  replicas: 1
  selector:
    matchLabels:
      app: redpanda-http-sink-connector
  template:
    metadata:
      labels:
        app: redpanda-http-sink-connector
    spec:
      containers:
        - name: http-sink-connector
          image: redpandadata/connectors:latest
          env:
            - name: CONNECT_BOOTSTRAP_SERVERS
              value: "redpanda-0.redpanda.redpanda.svc.cluster.local:9093,redpanda-1.redpanda.redpanda.svc.cluster.local:9093,redpanda-2.redpanda.redpanda.svc.cluster.local:9093"
            - name: CONNECT_CONFIGURATION
              value: |
                connector.client.config.override.policy=All
                key.converter=org.apache.kafka.connect.converters.ByteArrayConverter
                value.converter=org.apache.kafka.connect.converters.ByteArrayConverter
                group.id=connectors-cluster
                offset.storage.topic=_internal_connectors_offsets
                config.storage.topic=_internal_connectors_configs
                status.storage.topic=_internal_connectors_status
                config.storage.replication.factor=1
                offset.storage.replication.factor=1
                status.storage.replication.factor=1
            - name: CONNECT_ADDITIONAL_CONFIGURATION
              value: "config.storage.replication.factor=1,offset.storage.replication.factor=1,status.storage.replication.factor=1"
            - name: CONNECT_TLS_ENABLED
              value: "true"
            - name: CONNECT_TRUSTED_CERTS
              value: "ca.crt"
            - name: CONNECT_METRICS_ENABLED
              value: "true"
            - name: CONNECT_LOG_LEVEL
              value: "INFO"
            - name: CONNECT_PLUGIN_PATH
              value: "/opt/plugins/connect-plugins"
          volumeMounts:
            - name: redpanda-default-certs
              mountPath: "/opt/kafka/connect-certs/"
              readOnly: true
            - name: kafka-connect-plugins
              mountPath: "/opt/plugins"
              readOnly: true
      initContainers:
        - name: aiven-http-sink-installer
          image: busybox:latest
          env:
            - name: AIVEN_HTTP_SINK_VERSION
              value: 0.6.0
          command: ["/bin/sh", "-c"]
          args:
            - |
              set -xe
              TARGET_DIR="/mnt/plugins/connect-plugins"

              ### Wipe and refresh our Plugins directory.
              rm -Rf "${TARGET_DIR}"
              mkdir -p "${TARGET_DIR}"

              ### Fetch the HTTP Sink connector from GitHub.
              wget "https://github.com/Aiven-Open/http-connector-for-apache-kafka/releases/download/v${AIVEN_HTTP_SINK_VERSION}/http-connector-for-apache-kafka-${AIVEN_HTTP_SINK_VERSION}.tar"
              tar -xf "http-connector-for-apache-kafka-${AIVEN_HTTP_SINK_VERSION}.tar"

              ### Drop the version number from the directory and shorten the name.
              mv "http-connector-for-apache-kafka-${AIVEN_HTTP_SINK_VERSION}" "${TARGET_DIR}/http-connector"
          volumeMounts:
            - name: kafka-connect-plugins
              mountPath: "/mnt/plugins"
      volumes:
        - name: redpanda-default-certs
          secret:
            items:
              - key: ca.crt
                path: ca.crt
            secretName: redpanda-default-root-certificate
            defaultMode: 0440
        - name: kafka-connect-plugins
          emptyDir:
            sizeLimit: 100Mi
